### ISSUE TITLE
installation failed 

### ISSUE THREAD

**Issue by Ada-Codina** [aad-for-linux/libnss-aad#7]
from make command
```
gcc   -I. -fPIC -fno-stack-protector -Wall \
        -shared -Wl,--export-dynamic -o libnss_aad.so.2 -Wl,-soname,libnss_aad.so.2 \
        libnss_aad.c -lcrypt -lcurl -ljansson -lm -lsds -lsodium -lxcrypt
libnss_aad.c:2:10: fatal error: curl/curl.h: No such file or directory
    2 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:15: libnss_aad] Error 1
```

**Comment by oxr463** [comment]
It appears that the curl library headers are missing. The exact package name depends on your distribution, but you'll need to install the curl development package. For Ubuntu 20.04 LTS, it would be this one: https://packages.ubuntu.com/focal/libcurl4-openssl-dev

**Comment by Ada-Codina** [comment]
gcc   -I. -fPIC -fno-stack-protector -Wall \
        -shared -Wl,--export-dynamic -o libnss_aad.so.2 -Wl,-soname,libnss_aad.so.2 \
        libnss_aad.c -lcrypt -lcurl -ljansson -lm -lsds -lsodium -lxcrypt
libnss_aad.c:6:10: fatal error: jansson.h: No such file or directory
    6 | #include <jansson.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:15: libnss_aad] Error 1

what would be jansson.h?

**Comment by oxr463** [comment]
> what would be jansson.h?

That would be `libjansson-dev` per https://github.com/aad-for-linux/libnss-aad/blob/master/docker/ubuntu/Dockerfile#L18

**Comment by flexwie** [comment]
I have the same issue with sds.h.
I'm not experienced with C code and don't know where to find that package. I'm on Debian 10.
